return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cpp",
        "cmake",
        "css",
        "dockerfile",
        "go",
        "gomod",
        "gosum",
        "html",
        "java",
        "javascript",
        "json",
        "json5",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "php",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
        "zig",
      },
    },
  },

  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        clangd = {},
        pyright = {},
        vtsls = {},
        html = {},
        cssls = {},
        jsonls = {},
        yamlls = {},
        bashls = {},
        lua_ls = {},
        rust_analyzer = {},
        gopls = {},
        jdtls = {},
        intelephense = {},
        dockerls = {},
        tailwindcss = {},
        kotlin_language_server = {},
        ruby_lsp = {},
        zls = {},
        neocmake = {},
      },
    },
  },

  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "clangd",
        "clang-format",
        "pyright",
        "ruff",
        "black",
        "typescript-language-server",
        "prettier",
        "eslint-lsp",
        "html-lsp",
        "css-lsp",
        "json-lsp",
        "yaml-language-server",
        "bash-language-server",
        "lua-language-server",
        "stylua",
        "rust-analyzer",
        "gopls",
        "gofumpt",
        "jdtls",
        "intelephense",
        "dockerfile-language-server",
        "tailwindcss-language-server",
        "kotlin-language-server",
        "ruby-lsp",
        "zls",
        "cmakelang",
        "cmakelint",
        "shfmt",
        "shellcheck",
        "sql-formatter",
      },
    },
  },

  {
    "saghen/blink.cmp",
    opts = {
      completion = {
        documentation = {
          auto_show = true,
          auto_show_delay_ms = 200,
        },
        menu = {
          auto_show = true,
        },
      },
      sources = {
        default = {
          "lsp",
          "path",
          "snippets",
          "buffer",
        },
      },
    },
  },
}
